/**
 * 모든 (비커스텀) 칵테일의 맛 벡터·ABV 를 flavorModel 로 재계산.
 *   npm run db:recompute-flavor                 # DRY RUN (기본) — 표/통계 출력 + SQL 파일 생성
 *   npm run db:recompute-flavor -- --write      # 실제 UPDATE
 *   --sql=<path>                                # SQL 출력 경로 (기본: prisma/recompute-flavor.sql)
 */
import * as dotenv from "dotenv";
dotenv.config();

import { writeFileSync } from "node:fs";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { computeFlavorFromAmounts, mapDbMethod } from "../src/shared/lib/flavorModel";

const AXES = ["sweetness", "sourness", "bitterness", "strength", "freshness"] as const;
type Axis = (typeof AXES)[number];

function stats(vals: number[]): { min: number; mean: number; max: number } {
  const min = Math.min(...vals);
  const max = Math.max(...vals);
  const mean = vals.reduce((s, v) => s + v, 0) / (vals.length || 1);
  return { min, mean, max };
}
const f2 = (v: number): string => v.toFixed(2);

async function main(): Promise<void> {
  const write = process.argv.includes("--write");
  const sqlArg = process.argv.find((a) => a.startsWith("--sql="));
  const sqlPath = sqlArg ? sqlArg.slice(6) : "prisma/recompute-flavor.sql";

  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });

  try {
    const cocktails = await prisma.cocktail.findMany({
      where: { isCustom: false },
      include: { ingredients: { include: { ingredient: true } } },
      orderBy: { name: "asc" },
    });

    interface Row {
      id: string; name: string; method: string;
      before: Record<Axis | "abv", number>;
      after: Record<Axis | "abv", number>;
      unknown: string[];
    }
    const rows: Row[] = [];
    const unknownAll = new Set<string>();

    for (const c of cocktails) {
      const r = computeFlavorFromAmounts(
        c.ingredients.map((ci) => ({ name: ci.ingredient.name, amount: ci.amount })),
        mapDbMethod(c.method),
      );
      r.unknown.forEach((u) => unknownAll.add(u));
      rows.push({
        id: c.id, name: c.name, method: c.method ?? "-",
        before: { sweetness: c.sweetness, sourness: c.sourness, bitterness: c.bitterness, strength: c.strength, freshness: c.freshness, abv: c.abv },
        after: { sweetness: r.sweetness, sourness: r.sourness, bitterness: r.bitterness, strength: r.strength, freshness: r.freshness, abv: r.abv },
        unknown: r.unknown,
      });
    }

    console.log(`${write ? "WRITE" : "DRY RUN"} — ${rows.length} cocktails\n`);
    console.log("name".padEnd(18) + "method".padEnd(10) + "abv".padEnd(13) + AXES.map((a) => a.slice(0, 5).padEnd(12)).join(""));
    for (const r of rows) {
      const cells = AXES.map((a) => `${f2(r.before[a])}>${f2(r.after[a])}`.padEnd(12)).join("");
      console.log(r.name.padEnd(18) + r.method.padEnd(10) + `${r.before.abv.toFixed(1)}>${r.after.abv.toFixed(1)}`.padEnd(13) + cells);
    }

    console.log("\nper-axis  (before: min/mean/max)  ->  (after: min/mean/max)");
    for (const a of [...AXES, "abv" as const]) {
      const b = stats(rows.map((r) => r.before[a]));
      const n = stats(rows.map((r) => r.after[a]));
      console.log(`${a.padEnd(11)} ${f2(b.min)}/${f2(b.mean)}/${f2(b.max)}  ->  ${f2(n.min)}/${f2(n.mean)}/${f2(n.max)}`);
    }

    // 감정 목표 보정용 분위수 표 (0,10,...,100 퍼센타일) — src/shared/lib/emotionTaste.ts 의 FLAVOR_QUANTILES 에 붙여넣기
    console.log("\nFLAVOR_QUANTILES (after):");
    for (const a of AXES) {
      const sorted = rows.map((r) => r.after[a]).sort((x, y) => x - y);
      const q = Array.from({ length: 11 }, (_, i) => {
        const pos = (i / 10) * (sorted.length - 1);
        const lo = Math.floor(pos), hi = Math.ceil(pos);
        return Math.round((sorted[lo] + (sorted[hi] - sorted[lo]) * (pos - lo)) * 100) / 100;
      });
      console.log(`  ${a}: [${q.join(", ")}],`);
    }

    console.log(`\nunknown ingredient names: ${unknownAll.size === 0 ? "(none)" : [...unknownAll].join(", ")}`);

    const esc = (s: string): string => s.replace(/'/g, "''");
    const sql = [
      "-- generated by prisma/recompute-flavor.ts (flavorModel)",
      "BEGIN;",
      ...rows.map((r) =>
        `UPDATE "Cocktail" SET sweetness=${r.after.sweetness}, sourness=${r.after.sourness}, bitterness=${r.after.bitterness}, strength=${r.after.strength}, freshness=${r.after.freshness}, abv=${r.after.abv} WHERE id='${esc(r.id)}'; -- ${esc(r.name)}`),
      "COMMIT;",
      "",
    ].join("\n");
    writeFileSync(sqlPath, sql);
    console.log(`SQL written: ${sqlPath}`);

    if (!write) {
      console.log("\n(dry run — nothing written. pass --write to apply)");
      return;
    }
    if (unknownAll.size > 0) throw new Error("unknown ingredient names present — refusing to write");
    await prisma.$transaction(
      rows.map((r) =>
        prisma.cocktail.update({
          where: { id: r.id },
          data: { ...r.after },
        }),
      ),
    );
    console.log(`updated ${rows.length} cocktails`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
